# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from intera_core_msgs/HeadState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HeadState(genpy.Message):
  _md5sum = "51024ade10ffefe117049c9ba6fd743c"
  _type = "intera_core_msgs/HeadState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 pan
bool isTurning

# isBlocked will be true during active cancellation when the desired head position
# can not be reached because of j0's current position
bool isBlocked

# panMode will be one of
uint8 PASSIVE_MODE             = 0
uint8 ACTIVE_MODE              = 1
uint8 ACTIVE_CANCELLATION_MODE = 2
#
uint8 panMode


"""
  # Pseudo-constants
  PASSIVE_MODE = 0
  ACTIVE_MODE = 1
  ACTIVE_CANCELLATION_MODE = 2

  __slots__ = ['pan','isTurning','isBlocked','panMode']
  _slot_types = ['float32','bool','bool','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pan,isTurning,isBlocked,panMode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HeadState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pan is None:
        self.pan = 0.
      if self.isTurning is None:
        self.isTurning = False
      if self.isBlocked is None:
        self.isBlocked = False
      if self.panMode is None:
        self.panMode = 0
    else:
      self.pan = 0.
      self.isTurning = False
      self.isBlocked = False
      self.panMode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f3B().pack(_x.pan, _x.isTurning, _x.isBlocked, _x.panMode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.pan, _x.isTurning, _x.isBlocked, _x.panMode,) = _get_struct_f3B().unpack(str[start:end])
      self.isTurning = bool(self.isTurning)
      self.isBlocked = bool(self.isBlocked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f3B().pack(_x.pan, _x.isTurning, _x.isBlocked, _x.panMode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.pan, _x.isTurning, _x.isBlocked, _x.panMode,) = _get_struct_f3B().unpack(str[start:end])
      self.isTurning = bool(self.isTurning)
      self.isBlocked = bool(self.isBlocked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f3B = None
def _get_struct_f3B():
    global _struct_f3B
    if _struct_f3B is None:
        _struct_f3B = struct.Struct("<f3B")
    return _struct_f3B
