; Auto-generated. Do not edit!


(cl:in-package intera_motion_msgs-msg)


;//! \htmlinclude MotionCommandFeedback.msg.html

(cl:defclass <MotionCommandFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type intera_motion_msgs-msg:MotionStatus
    :initform (cl:make-instance 'intera_motion_msgs-msg:MotionStatus)))
)

(cl:defclass MotionCommandFeedback (<MotionCommandFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotionCommandFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotionCommandFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name intera_motion_msgs-msg:<MotionCommandFeedback> is deprecated: use intera_motion_msgs-msg:MotionCommandFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <MotionCommandFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader intera_motion_msgs-msg:status-val is deprecated.  Use intera_motion_msgs-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotionCommandFeedback>) ostream)
  "Serializes a message object of type '<MotionCommandFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotionCommandFeedback>) istream)
  "Deserializes a message object of type '<MotionCommandFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotionCommandFeedback>)))
  "Returns string type for a message object of type '<MotionCommandFeedback>"
  "intera_motion_msgs/MotionCommandFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotionCommandFeedback)))
  "Returns string type for a message object of type 'MotionCommandFeedback"
  "intera_motion_msgs/MotionCommandFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotionCommandFeedback>)))
  "Returns md5sum for a message object of type '<MotionCommandFeedback>"
  "896254458c1272a4b412118474588e67")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotionCommandFeedback)))
  "Returns md5sum for a message object of type 'MotionCommandFeedback"
  "896254458c1272a4b412118474588e67")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotionCommandFeedback>)))
  "Returns full string definition for message of type '<MotionCommandFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%MotionStatus status~%~%~%================================================================================~%MSG: intera_motion_msgs/MotionStatus~%# motion status~%Header header~%string motion_status~%string current_trajectory~%uint32 current_waypoint~%uint32 motion_request~%~%# motion_status enum values:~%string MOTION_IDLE=idle~%string MOTION_PENDING=pending~%string MOTION_RUNNING=running~%string MOTION_STOPPING=stopping~%string MOTION_DONE=done~%string MOTION_PREEMPTED=preempted~%string MOTION_ERROR=error~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotionCommandFeedback)))
  "Returns full string definition for message of type 'MotionCommandFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%MotionStatus status~%~%~%================================================================================~%MSG: intera_motion_msgs/MotionStatus~%# motion status~%Header header~%string motion_status~%string current_trajectory~%uint32 current_waypoint~%uint32 motion_request~%~%# motion_status enum values:~%string MOTION_IDLE=idle~%string MOTION_PENDING=pending~%string MOTION_RUNNING=running~%string MOTION_STOPPING=stopping~%string MOTION_DONE=done~%string MOTION_PREEMPTED=preempted~%string MOTION_ERROR=error~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotionCommandFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotionCommandFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MotionCommandFeedback
    (cl:cons ':status (status msg))
))
