(cl:in-package intera_core_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTERACTION_CONTROL_ACTIVE-VAL
          INTERACTION_CONTROL_ACTIVE
          K_IMPEDANCE-VAL
          K_IMPEDANCE
          D_IMPEDANCE-VAL
          D_IMPEDANCE
          ENDPOINT_FORCE_COMMAND-VAL
          ENDPOINT_FORCE_COMMAND
          ENDPOINT_NAME-VAL
          ENDPOINT_NAME
          IN_ENDPOINT_FRAME-VAL
          IN_ENDPOINT_FRAME
          DISABLE_DAMPING_IN_FORCE_CONTROL-VAL
          DISABLE_DAMPING_IN_FORCE_CONTROL
          DISABLE_REFERENCE_RESETTING-VAL
          DISABLE_REFERENCE_RESETTING
          ROTATIONS_FOR_CONSTRAINED_ZEROG-VAL
          ROTATIONS_FOR_CONSTRAINED_ZEROG
))