//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the intera_interface package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __intera_interface__SAWYERVELOCITYJOINTTRAJECTORYACTIONSERVERCONFIG_H__
#define __intera_interface__SAWYERVELOCITYJOINTTRAJECTORYACTIONSERVERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace intera_interface
{
  class SawyerVelocityJointTrajectoryActionServerConfigStatics;

  class SawyerVelocityJointTrajectoryActionServerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(SawyerVelocityJointTrajectoryActionServerConfig &config, const SawyerVelocityJointTrajectoryActionServerConfig &max, const SawyerVelocityJointTrajectoryActionServerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const SawyerVelocityJointTrajectoryActionServerConfig &config1, const SawyerVelocityJointTrajectoryActionServerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, SawyerVelocityJointTrajectoryActionServerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const SawyerVelocityJointTrajectoryActionServerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SawyerVelocityJointTrajectoryActionServerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const SawyerVelocityJointTrajectoryActionServerConfig &config) const = 0;
      virtual void getValue(const SawyerVelocityJointTrajectoryActionServerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T SawyerVelocityJointTrajectoryActionServerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (SawyerVelocityJointTrajectoryActionServerConfig::* field);

      virtual void clamp(SawyerVelocityJointTrajectoryActionServerConfig &config, const SawyerVelocityJointTrajectoryActionServerConfig &max, const SawyerVelocityJointTrajectoryActionServerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const SawyerVelocityJointTrajectoryActionServerConfig &config1, const SawyerVelocityJointTrajectoryActionServerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, SawyerVelocityJointTrajectoryActionServerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const SawyerVelocityJointTrajectoryActionServerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SawyerVelocityJointTrajectoryActionServerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const SawyerVelocityJointTrajectoryActionServerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const SawyerVelocityJointTrajectoryActionServerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, SawyerVelocityJointTrajectoryActionServerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, SawyerVelocityJointTrajectoryActionServerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<SawyerVelocityJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(SawyerVelocityJointTrajectoryActionServerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("goal_time"==(*_i)->name){goal_time = boost::any_cast<double>(val);}
        if("stopped_velocity_tolerance"==(*_i)->name){stopped_velocity_tolerance = boost::any_cast<double>(val);}
        if("right_j0_goal"==(*_i)->name){right_j0_goal = boost::any_cast<double>(val);}
        if("right_j1_goal"==(*_i)->name){right_j1_goal = boost::any_cast<double>(val);}
        if("right_j2_goal"==(*_i)->name){right_j2_goal = boost::any_cast<double>(val);}
        if("right_j3_goal"==(*_i)->name){right_j3_goal = boost::any_cast<double>(val);}
        if("right_j4_goal"==(*_i)->name){right_j4_goal = boost::any_cast<double>(val);}
        if("right_j5_goal"==(*_i)->name){right_j5_goal = boost::any_cast<double>(val);}
        if("right_j6_goal"==(*_i)->name){right_j6_goal = boost::any_cast<double>(val);}
        if("right_j0_trajectory"==(*_i)->name){right_j0_trajectory = boost::any_cast<double>(val);}
        if("right_j1_trajectory"==(*_i)->name){right_j1_trajectory = boost::any_cast<double>(val);}
        if("right_j2_trajectory"==(*_i)->name){right_j2_trajectory = boost::any_cast<double>(val);}
        if("right_j3_trajectory"==(*_i)->name){right_j3_trajectory = boost::any_cast<double>(val);}
        if("right_j4_trajectory"==(*_i)->name){right_j4_trajectory = boost::any_cast<double>(val);}
        if("right_j5_trajectory"==(*_i)->name){right_j5_trajectory = boost::any_cast<double>(val);}
        if("right_j6_trajectory"==(*_i)->name){right_j6_trajectory = boost::any_cast<double>(val);}
        if("right_j0_kp"==(*_i)->name){right_j0_kp = boost::any_cast<double>(val);}
        if("right_j0_ki"==(*_i)->name){right_j0_ki = boost::any_cast<double>(val);}
        if("right_j0_kd"==(*_i)->name){right_j0_kd = boost::any_cast<double>(val);}
        if("right_j1_kp"==(*_i)->name){right_j1_kp = boost::any_cast<double>(val);}
        if("right_j1_ki"==(*_i)->name){right_j1_ki = boost::any_cast<double>(val);}
        if("right_j1_kd"==(*_i)->name){right_j1_kd = boost::any_cast<double>(val);}
        if("right_j2_kp"==(*_i)->name){right_j2_kp = boost::any_cast<double>(val);}
        if("right_j2_ki"==(*_i)->name){right_j2_ki = boost::any_cast<double>(val);}
        if("right_j2_kd"==(*_i)->name){right_j2_kd = boost::any_cast<double>(val);}
        if("right_j3_kp"==(*_i)->name){right_j3_kp = boost::any_cast<double>(val);}
        if("right_j3_ki"==(*_i)->name){right_j3_ki = boost::any_cast<double>(val);}
        if("right_j3_kd"==(*_i)->name){right_j3_kd = boost::any_cast<double>(val);}
        if("right_j4_kp"==(*_i)->name){right_j4_kp = boost::any_cast<double>(val);}
        if("right_j4_ki"==(*_i)->name){right_j4_ki = boost::any_cast<double>(val);}
        if("right_j4_kd"==(*_i)->name){right_j4_kd = boost::any_cast<double>(val);}
        if("right_j5_kp"==(*_i)->name){right_j5_kp = boost::any_cast<double>(val);}
        if("right_j5_ki"==(*_i)->name){right_j5_ki = boost::any_cast<double>(val);}
        if("right_j5_kd"==(*_i)->name){right_j5_kd = boost::any_cast<double>(val);}
        if("right_j6_kp"==(*_i)->name){right_j6_kp = boost::any_cast<double>(val);}
        if("right_j6_ki"==(*_i)->name){right_j6_ki = boost::any_cast<double>(val);}
        if("right_j6_kd"==(*_i)->name){right_j6_kd = boost::any_cast<double>(val);}
      }
    }

    double goal_time;
double stopped_velocity_tolerance;
double right_j0_goal;
double right_j1_goal;
double right_j2_goal;
double right_j3_goal;
double right_j4_goal;
double right_j5_goal;
double right_j6_goal;
double right_j0_trajectory;
double right_j1_trajectory;
double right_j2_trajectory;
double right_j3_trajectory;
double right_j4_trajectory;
double right_j5_trajectory;
double right_j6_trajectory;
double right_j0_kp;
double right_j0_ki;
double right_j0_kd;
double right_j1_kp;
double right_j1_ki;
double right_j1_kd;
double right_j2_kp;
double right_j2_ki;
double right_j2_kd;
double right_j3_kp;
double right_j3_ki;
double right_j3_kd;
double right_j4_kp;
double right_j4_ki;
double right_j4_kd;
double right_j5_kp;
double right_j5_ki;
double right_j5_kd;
double right_j6_kp;
double right_j6_ki;
double right_j6_kd;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_time;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stopped_velocity_tolerance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j2_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j3_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j4_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j5_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j6_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j2_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j3_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j4_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j5_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j6_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j0_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j0_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j0_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j1_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j1_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j1_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j2_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j2_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j2_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j3_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j3_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j3_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j4_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j4_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j4_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j5_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j5_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j5_kd;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j6_kp;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j6_ki;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_j6_kd;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("SawyerVelocityJointTrajectoryActionServerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const SawyerVelocityJointTrajectoryActionServerConfig &__max__ = __getMax__();
      const SawyerVelocityJointTrajectoryActionServerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const SawyerVelocityJointTrajectoryActionServerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const SawyerVelocityJointTrajectoryActionServerConfig &__getDefault__();
    static const SawyerVelocityJointTrajectoryActionServerConfig &__getMax__();
    static const SawyerVelocityJointTrajectoryActionServerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const SawyerVelocityJointTrajectoryActionServerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<std::string>::clamp(SawyerVelocityJointTrajectoryActionServerConfig &config, const SawyerVelocityJointTrajectoryActionServerConfig &max, const SawyerVelocityJointTrajectoryActionServerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class SawyerVelocityJointTrajectoryActionServerConfigStatics
  {
    friend class SawyerVelocityJointTrajectoryActionServerConfig;

    SawyerVelocityJointTrajectoryActionServerConfigStatics()
    {
SawyerVelocityJointTrajectoryActionServerConfig::GroupDescription<SawyerVelocityJointTrajectoryActionServerConfig::DEFAULT, SawyerVelocityJointTrajectoryActionServerConfig> Default("Default", "", 0, 0, true, &SawyerVelocityJointTrajectoryActionServerConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_time = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_time = 120.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_time = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("goal_time", "double", 0, "Amount of time (s) controller is permitted to be late achieving goal", "", &SawyerVelocityJointTrajectoryActionServerConfig::goal_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("goal_time", "double", 0, "Amount of time (s) controller is permitted to be late achieving goal", "", &SawyerVelocityJointTrajectoryActionServerConfig::goal_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stopped_velocity_tolerance = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stopped_velocity_tolerance = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stopped_velocity_tolerance = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("stopped_velocity_tolerance", "double", 0, "Maximum velocity (m/s) at end of trajectory to be considered stopped", "", &SawyerVelocityJointTrajectoryActionServerConfig::stopped_velocity_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("stopped_velocity_tolerance", "double", 0, "Maximum velocity (m/s) at end of trajectory to be considered stopped", "", &SawyerVelocityJointTrajectoryActionServerConfig::stopped_velocity_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j0_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_goal", "double", 0, "right_j0 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_goal", "double", 0, "right_j0 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j1_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_goal", "double", 0, "right_j1 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_goal", "double", 0, "right_j1 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j2_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j2_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j2_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_goal", "double", 0, "right_j2 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_goal", "double", 0, "right_j2 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j3_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j3_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j3_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_goal", "double", 0, "right_j3 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_goal", "double", 0, "right_j3 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j4_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j4_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j4_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_goal", "double", 0, "right_j4 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_goal", "double", 0, "right_j4 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j5_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j5_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j5_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_goal", "double", 0, "right_j5 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_goal", "double", 0, "right_j5 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j6_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j6_goal = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j6_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_goal", "double", 0, "right_j6 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_goal", "double", 0, "right_j6 - maximum final error", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j0_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_trajectory", "double", 0, "right_j0 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_trajectory", "double", 0, "right_j0 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j1_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_trajectory", "double", 0, "right_j1 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_trajectory", "double", 0, "right_j1 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j2_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j2_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j2_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_trajectory", "double", 0, "right_j2 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_trajectory", "double", 0, "right_j2 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j3_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j3_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j3_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_trajectory", "double", 0, "right_j3 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_trajectory", "double", 0, "right_j3 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j4_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j4_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j4_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_trajectory", "double", 0, "right_j4 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_trajectory", "double", 0, "right_j4 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j5_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j5_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j5_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_trajectory", "double", 0, "right_j5 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_trajectory", "double", 0, "right_j5 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j6_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j6_trajectory = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j6_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_trajectory", "double", 0, "right_j6 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_trajectory", "double", 0, "right_j6 - maximum error during trajectory execution", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j0_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j0_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j0_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_kp", "double", 0, "right_j0 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_kp", "double", 0, "right_j0 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j0_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j0_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j0_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_ki", "double", 0, "right_j0 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_ki", "double", 0, "right_j0 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j0_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j0_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j0_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_kd", "double", 0, "right_j0 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j0_kd", "double", 0, "right_j0 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j0_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j1_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j1_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j1_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_kp", "double", 0, "right_j1 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_kp", "double", 0, "right_j1 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j1_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j1_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j1_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_ki", "double", 0, "right_j1 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_ki", "double", 0, "right_j1 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j1_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j1_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j1_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_kd", "double", 0, "right_j1 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j1_kd", "double", 0, "right_j1 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j1_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j2_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j2_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j2_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_kp", "double", 0, "right_j2 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_kp", "double", 0, "right_j2 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j2_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j2_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j2_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_ki", "double", 0, "right_j2 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_ki", "double", 0, "right_j2 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j2_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j2_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j2_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_kd", "double", 0, "right_j2 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j2_kd", "double", 0, "right_j2 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j2_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j3_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j3_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j3_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_kp", "double", 0, "right_j3 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_kp", "double", 0, "right_j3 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j3_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j3_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j3_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_ki", "double", 0, "right_j3 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_ki", "double", 0, "right_j3 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j3_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j3_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j3_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_kd", "double", 0, "right_j3 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j3_kd", "double", 0, "right_j3 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j3_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j4_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j4_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j4_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_kp", "double", 0, "right_j4 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_kp", "double", 0, "right_j4 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j4_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j4_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j4_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_ki", "double", 0, "right_j4 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_ki", "double", 0, "right_j4 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j4_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j4_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j4_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_kd", "double", 0, "right_j4 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j4_kd", "double", 0, "right_j4 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j4_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j5_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j5_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j5_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_kp", "double", 0, "right_j5 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_kp", "double", 0, "right_j5 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j5_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j5_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j5_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_ki", "double", 0, "right_j5 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_ki", "double", 0, "right_j5 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j5_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j5_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j5_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_kd", "double", 0, "right_j5 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j5_kd", "double", 0, "right_j5 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j5_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j6_kp = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j6_kp = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j6_kp = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_kp", "double", 0, "right_j6 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_kp", "double", 0, "right_j6 - Kp proportional control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_kp)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j6_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j6_ki = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j6_ki = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_ki", "double", 0, "right_j6 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_ki", "double", 0, "right_j6 - Ki integral control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_ki)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_j6_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_j6_kd = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_j6_kd = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_kd", "double", 0, "right_j6 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_kd)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::ParamDescription<double>("right_j6_kd", "double", 0, "right_j6 - Kd derivative control gain", "", &SawyerVelocityJointTrajectoryActionServerConfig::right_j6_kd)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(SawyerVelocityJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr(new SawyerVelocityJointTrajectoryActionServerConfig::GroupDescription<SawyerVelocityJointTrajectoryActionServerConfig::DEFAULT, SawyerVelocityJointTrajectoryActionServerConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<SawyerVelocityJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<SawyerVelocityJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    SawyerVelocityJointTrajectoryActionServerConfig __max__;
    SawyerVelocityJointTrajectoryActionServerConfig __min__;
    SawyerVelocityJointTrajectoryActionServerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const SawyerVelocityJointTrajectoryActionServerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static SawyerVelocityJointTrajectoryActionServerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &SawyerVelocityJointTrajectoryActionServerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const SawyerVelocityJointTrajectoryActionServerConfig &SawyerVelocityJointTrajectoryActionServerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const SawyerVelocityJointTrajectoryActionServerConfig &SawyerVelocityJointTrajectoryActionServerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const SawyerVelocityJointTrajectoryActionServerConfig &SawyerVelocityJointTrajectoryActionServerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<SawyerVelocityJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr> &SawyerVelocityJointTrajectoryActionServerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<SawyerVelocityJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> &SawyerVelocityJointTrajectoryActionServerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const SawyerVelocityJointTrajectoryActionServerConfigStatics *SawyerVelocityJointTrajectoryActionServerConfig::__get_statics__()
  {
    const static SawyerVelocityJointTrajectoryActionServerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = SawyerVelocityJointTrajectoryActionServerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __SAWYERVELOCITYJOINTTRAJECTORYACTIONSERVERRECONFIGURATOR_H__
