(cl:defpackage intera_core_msgs-srv
  (:use )
  (:export
   "IOCOMPONENTCOMMANDSRV"
   "<IOCOMPONENTCOMMANDSRV-REQUEST>"
   "IOCOMPONENTCOMMANDSRV-REQUEST"
   "<IOCOMPONENTCOMMANDSRV-RESPONSE>"
   "IOCOMPONENTCOMMANDSRV-RESPONSE"
   "SOLVEPOSITIONFK"
   "<SOLVEPOSITIONFK-REQUEST>"
   "SOLVEPOSITIONFK-REQUEST"
   "<SOLVEPOSITIONFK-RESPONSE>"
   "SOLVEPOSITIONFK-RESPONSE"
   "SOLVEPOSITIONIK"
   "<SOLVEPOSITIONIK-REQUEST>"
   "SOLVEPOSITIONIK-REQUEST"
   "<SOLVEPOSITIONIK-RESPONSE>"
   "SOLVEPOSITIONIK-RESPONSE"
  ))

