// Generated by gencpp from file intera_core_msgs/HomingCommand.msg
// DO NOT EDIT!


#ifndef INTERA_CORE_MSGS_MESSAGE_HOMINGCOMMAND_H
#define INTERA_CORE_MSGS_MESSAGE_HOMINGCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intera_core_msgs
{
template <class ContainerAllocator>
struct HomingCommand_
{
  typedef HomingCommand_<ContainerAllocator> Type;

  HomingCommand_()
    : name()
    , command()  {
    }
  HomingCommand_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _command_type;
  _command_type command;



  enum {
    MANUAL = 1,
    AUTO = 2,
    NONE = 0,
  };


  typedef boost::shared_ptr< ::intera_core_msgs::HomingCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intera_core_msgs::HomingCommand_<ContainerAllocator> const> ConstPtr;

}; // struct HomingCommand_

typedef ::intera_core_msgs::HomingCommand_<std::allocator<void> > HomingCommand;

typedef boost::shared_ptr< ::intera_core_msgs::HomingCommand > HomingCommandPtr;
typedef boost::shared_ptr< ::intera_core_msgs::HomingCommand const> HomingCommandConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intera_core_msgs::HomingCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace intera_core_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'intera_core_msgs': ['/home/cthornton/sawyer_ws/src/intera_common/intera_core_msgs/msg', '/home/cthornton/sawyer_ws/devel/share/intera_core_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::HomingCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::HomingCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::HomingCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff29c86109f0f4cada5bbde945dd55c4";
  }

  static const char* value(const ::intera_core_msgs::HomingCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff29c86109f0f4caULL;
  static const uint64_t static_value2 = 0xda5bbde945dd55c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intera_core_msgs/HomingCommand";
  }

  static const char* value(const ::intera_core_msgs::HomingCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message is used to command the homing state of all joints on the robot.\n\
# For each joint in the name array the corresponding value in the command\n\
# sets the homing mode for that joint.\n\
# MANUAL disengages the joint brake and puts the joint in a \"gumby\" mode.\n\
# AUTO disengages the joint brake and automatically homes the joint.\n\
# If a joint is already homed the command has no effect.\n\
string[] name\n\
int32[]  command\n\
# Valid homing commands:\n\
int32 MANUAL=1\n\
int32 AUTO=2\n\
# Invalid, value is used internally:\n\
int32 NONE=0\n\
\n\
\n\
";
  }

  static const char* value(const ::intera_core_msgs::HomingCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomingCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intera_core_msgs::HomingCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intera_core_msgs::HomingCommand_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "command[]" << std::endl;
    for (size_t i = 0; i < v.command.size(); ++i)
    {
      s << indent << "  command[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.command[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERA_CORE_MSGS_MESSAGE_HOMINGCOMMAND_H
